name: Artifact
run-name: Saving Artifact

on:
  push:
    branches: [feature/**]

jobs:
  validate-language:
    uses: JairoRamirezC/ejercicios-pipeline/blob/feature/new-pipeline/.github/workflows/context.yml
    with:
      language: 'python'

  constructor:
    needs: validate-language
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      - name: Upload File
        uses: actions/upload-artifact@v7
        with:
          name: my-aplication
          path: resultados.txt
  
  deployment:
    needs: constructor
    runs-on: ubuntu-latest
    steps:
      - name: Download File
        uses: actions/download-artifact@v8
        with:
          name: my-aplication
      - name: Reading File
        run: |
          ls -l
          cat resultados.txt