name: Pipeline for Deploy to AWS Cloud
run-name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Despligue Pruebas
        run: echo "Instalando la aplicación en el servidor de pruebas (Staging)..."

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Despliegue produccion
        run: echo "¡Aprobación recibida! Desplegando en los servidores de producción de AWS."