name: Deploy to AWS
run-name: Deploy to AWS

on:
  push:
    branches:
      - feature/**

jobs:
  validating-aws:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Pipeline para aws
        run: echo "Pipeline para desplegar a production en aws"