name: Security Template
run-name: Security Template

on:
  workflow_call:
    inputs:
      programing_lenguage:
        type: string
        description: 'Lenguaje de programacion'
        required: true
        default: 'Python'

jobs:
  scan-lenguage:
    runs-on: ubuntu-latest
    steps:
      - name: Scan Lenguage Programing
        run: echo 'Escaneando vulnerabilidades para el lenguaje:${{inputs.programing_lenguage}}'